### ISSUE TITLE
Cannot Update default payment method

### ISSUE THREAD

**Issue by sparkline-charlie** [braintree/braintree_python#66] opened 2016-01-28 03:38 UTC
Hi,

Hope you can find some time to check on my problem.

Currently, i'm creating a maintenance application and display the payment method used by clients. Clients may have multiple payment method.

![image](https://cloud.githubusercontent.com/assets/15224937/12634274/f92e6b26-c5b2-11e5-8f59-aaf9bbb0fd83.png)

My concern here is i am not able to update the default payment method for the selected customer using this code.

result = braintree.CreditCard.update(token,{
        "options": {
            "make_default": True,
        },
    })

After checking the command prompt for any logs. I've found this

![image](https://cloud.githubusercontent.com/assets/15224937/12634323/6a906b7a-c5b3-11e5-9a1e-8e7773254586.png)

Below is the complete code of the method i've used.

![image](https://cloud.githubusercontent.com/assets/15224937/12634336/88977d34-c5b3-11e5-864b-3043682e7f56.png)

Hope you can assist me.
Thanks!

**Comment by crookedneighbor** [comment] 2016-01-28 16:58
So far I have not been able to reproduce your issue. This code prints "success":

```python
import braintree

braintree.Configuration.configure(
    braintree.Environment.Sandbox,
    "merchant_id",
    "public_key",
    "private_key"
)

token = "some-token"

result = braintree.CreditCard.update(token,{
    "options": {
        "make_default": True,
    },
})

if result.is_success:
    print 'success'
else:
    print 'error'
    print result.errors.size
    for error in result.errors.deep_errors:
        print error.code
```

You should contact [Braintree Support](https://support.braintreepayments.com/) since this seems to be a problem specific to your integration and not with the library. You can provide a link to this issue so they can quickly try to debug the issue. I'm going to close this issue, but the link to it will still be available for your and their reference.

As a side-note, I recommend switching from `CreditCard.update` to `PaymentMethod.update`. The `CreditCard` methods still work, but they are deprecated.

**Closed by crookedneighbor** 2016-01-28 16:58 UTC
